#!/usr/bin/env python3
"""
Dynamic residual compensation module for the SOFA digital twin.

The SOFA/mechanics model is kept as the primary physics-based soft sensor.
This module only predicts the residual between IMU and SOFA:

    residual = IMU - SOFA
    hybrid_tip = SOFA + predicted_residual

It loads parameters from dynamic_residual_model.json, generated by
train_dynamic_residual.py.
"""

import json
import time
import math


class DynamicResidualModel:
    def __init__(self, model_path="dynamic_residual_model.json"):
        self.model_path = model_path
        self.enabled = False

        self.features = []
        self.targets = []
        self.x_mean = []
        self.x_std = []
        self.W = []

        self.prev_t = None
        self.prev_cmd = [0.0, 0.0, 0.0]
        self.prev_actual = [0.0, 0.0, 0.0]
        self.prev_tip = [0.0, 0.0]
        self.prev_imu = [0.0, 0.0]
        self.prev_err = [0.0, 0.0]

        self.load(model_path)

    def load(self, model_path):
        try:
            with open(model_path, "r") as f:
                data = json.load(f)

            self.features = list(data["features"])
            self.targets = list(data.get("targets", ["err_roll", "err_pitch"]))
            self.x_mean = [float(x) for x in data["x_mean"]]
            self.x_std = [float(x) if abs(float(x)) > 1e-12 else 1.0 for x in data["x_std"]]
            self.W = data["W"]

            if len(self.W) != len(self.features) + 1:
                raise ValueError("W row count does not match features + bias")

            self.enabled = True
            print(f"[DynamicResidualModel] Loaded model: {model_path}")
            print(f"[DynamicResidualModel] Feature dimension: {len(self.features)}")
        except Exception as e:
            self.enabled = False
            print(f"[DynamicResidualModel] Failed to load model {model_path}: {e}")

    def reset_state(self):
        self.prev_t = None
        self.prev_cmd = [0.0, 0.0, 0.0]
        self.prev_actual = [0.0, 0.0, 0.0]
        self.prev_tip = [0.0, 0.0]
        self.prev_imu = [0.0, 0.0]
        self.prev_err = [0.0, 0.0]

    def _safe_vec(self, x, n, default=0.0):
        if x is None:
            return [float(default)] * n
        out = []
        for i in range(n):
            try:
                v = float(x[i])
                if not math.isfinite(v):
                    v = float(default)
            except Exception:
                v = float(default)
            out.append(v)
        return out

    def _matmul_aug(self, x_aug):
        # W shape: [num_features + 1, 2]
        y0 = 0.0
        y1 = 0.0
        for i, xi in enumerate(x_aug):
            wi = self.W[i]
            y0 += float(xi) * float(wi[0])
            y1 += float(xi) * float(wi[1])
        return [y0, y1]

    def _build_feature_dict(self, cmd, actual, sofa_tip, imu, now):
        if self.prev_t is None:
            dt = 1e-3
        else:
            dt = max(1e-3, now - self.prev_t)

        dcmd_dt = [(cmd[i] - self.prev_cmd[i]) / dt for i in range(3)]
        dactual_dt = [(actual[i] - self.prev_actual[i]) / dt for i in range(3)]

        sofa_roll, sofa_pitch = sofa_tip
        imu_roll, imu_pitch = imu

        return {
            "cmd0": cmd[0],
            "cmd1": cmd[1],
            "cmd2": cmd[2],

            "actual0": actual[0],
            "actual1": actual[1],
            "actual2": actual[2],

            "cmd0_prev": self.prev_cmd[0],
            "cmd1_prev": self.prev_cmd[1],
            "cmd2_prev": self.prev_cmd[2],

            "actual0_prev": self.prev_actual[0],
            "actual1_prev": self.prev_actual[1],
            "actual2_prev": self.prev_actual[2],

            "dcmd0_dt": dcmd_dt[0],
            "dcmd1_dt": dcmd_dt[1],
            "dcmd2_dt": dcmd_dt[2],

            "dactual0_dt": dactual_dt[0],
            "dactual1_dt": dactual_dt[1],
            "dactual2_dt": dactual_dt[2],

            "sofa_roll": sofa_roll,
            "sofa_pitch": sofa_pitch,

            "imu_roll": imu_roll,
            "imu_pitch": imu_pitch,

            "sofa_roll_prev": self.prev_tip[0],
            "sofa_pitch_prev": self.prev_tip[1],

            "imu_roll_prev": self.prev_imu[0],
            "imu_pitch_prev": self.prev_imu[1],

            "err_roll_prev": self.prev_err[0],
            "err_pitch_prev": self.prev_err[1],
        }

    def predict(self, cmd_mm, actual_mm, sofa_tip_deg, imu_deg=None, update_state=True):
        """
        Parameters
        ----------
        cmd_mm : list[float]
            Target tendon displacement [dL0, dL1, dL2] in mm.
        actual_mm : list[float]
            Real/solver tendon displacement [dL0, dL1, dL2] in mm.
        sofa_tip_deg : list[float]
            SOFA-predicted [roll, pitch] in deg.
        imu_deg : list[float] or None
            IMU-measured [roll, pitch] in deg. If None, previous IMU is used.
        update_state : bool
            Whether to update the internal dynamic history.

        Returns
        -------
        dict with keys:
            enabled, sofa_tip, predicted_residual, hybrid_tip, current_residual
        """
        cmd = self._safe_vec(cmd_mm, 3)
        actual = self._safe_vec(actual_mm, 3)
        sofa_tip = self._safe_vec(sofa_tip_deg, 2)
        imu = self._safe_vec(imu_deg, 2) if imu_deg is not None else list(self.prev_imu)
        now = time.time()

        current_residual = [imu[0] - sofa_tip[0], imu[1] - sofa_tip[1]]

        if not self.enabled:
            return {
                "enabled": False,
                "sofa_tip": sofa_tip,
                "predicted_residual": [0.0, 0.0],
                "hybrid_tip": sofa_tip,
                "current_residual": current_residual,
            }

        values = self._build_feature_dict(cmd, actual, sofa_tip, imu, now)
        x = [float(values.get(name, 0.0)) for name in self.features]
        x_norm = [(x[i] - self.x_mean[i]) / self.x_std[i] for i in range(len(x))]
        x_aug = x_norm + [1.0]

        predicted_residual = self._matmul_aug(x_aug)
        hybrid_tip = [
            sofa_tip[0] + predicted_residual[0],
            sofa_tip[1] + predicted_residual[1],
        ]

        if update_state:
            self.prev_t = now
            self.prev_cmd = list(cmd)
            self.prev_actual = list(actual)
            self.prev_tip = list(sofa_tip)
            self.prev_imu = list(imu)
            self.prev_err = list(current_residual)

        return {
            "enabled": True,
            "sofa_tip": sofa_tip,
            "predicted_residual": predicted_residual,
            "hybrid_tip": hybrid_tip,
            "current_residual": current_residual,
        }
